### ISSUE TITLE
Code assumes file in SNS subscription exists

### ISSUE THREAD

**Issue by Pcolar** [Pcolar/dpn-python-library#2]
There is not sufficient ewrror checking for the presence of a file object:

python dpn_python_shell.py 
2017-05-17-14-15-18:  Deleting message: 952fd32b-c5c9-59f3-98c4-82be32f42a09
Traceback (most recent call last):
  File "dpn_python_shell.py", line 9, in <module>
    download_s3_file(json_file)
  File "/home/dave/dpn-python-library/dpn_python_library.py", line 83, in download_s3_file
    s3.Object(s3_bucket, json_file).download_file(json_file)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 202, in object_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 126, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 299, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

**Comment by Pcolar** [comment]
fixed by PR Aws s3 file handling #3
