### ISSUE TITLE
Increase error checking on return

### ISSUE THREAD

**Issue by Pcolar** [Pcolar/dpn-python-library#4]
ERROR: S3 object not found dcv-snapshot-report-2017-06-09.json 

Test for error when exceptions found.

2017-06-09-08-35-34:  File created: dcv-snapshot-report-2017-06-09.csv
Traceback (most recent call last):
  File "/home/dave/dpn-python-library/dpn_python_shell.py", line 10, in <module>
    create_csv(json_file)
  File "/home/dave/dpn-python-library/dpn_python_library.py", line 60, in create_csv
    with open(json_file) as input_file:
IOError: [Errno 2] No such file or directory: u'dcv-snapshot-report-2017-06-09.json'

**Comment by Pcolar** [comment]
Incorporated in multiple changes
